# This is a basic workflow to help you get started with Actions

name: Deploy to production

# Controls when the action will run.
on:
  schedule:
    - cron: "0 7 * * 1,2,3,4,5"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-dev --no-interaction --optimize-autoloader
        env:
          COMPOSER_AUTH: '{"http-basic":{"source.woogostores.com":{"username":"${{ secrets.SATISPRESS_PASSWORD }}","password":"satispress"}}}'

      - name: ssh deploy
        # You may pin to the exact commit or the version.
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete  --exclude='/wp-cli.local.yml' --exclude='/backups' --exclude='/web/app/db.php' --exclude='/web/.well-known/' --exclude='/.env' --exclude='/web/app/uploads/' --exclude='/web/app/cache/' --exclude='/web/app/advanced-cache.php' --exclude='/web/app/object-cache.php'"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}